In [1]:
import sys
import os

# Agregar el directorio padre al sys.path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

import numpy as np
import pandas as pd
import seaborn as sns
from datetime import datetime


import cashia_core.data_channel.promok_datapipe_func as pkdp
import cashia_core.common_tools.pm_mxgeographic as pm_mxgeo

import mlp.promok_models_config as pkconfig
from mlp.dataframe_tracker import *


%matplotlib inline

In [2]:
import sklearn as sk

print("numpy:",np.__version__)
print("pandas:",pd.__version__)
print("seborn:",sns.__version__)
print("sklearn:",sk.__version__)
#print(":",.__version__)

numpy: 1.26.0
pandas: 1.5.3
seborn: 0.13.2
sklearn: 1.2.2

# 1 Procesar los datos

## 1.1 Lectura de los datos

### 1.1.1 Lectura de los datos de configuración

In [3]:
print('Configuration file: ', pkconfig.configuration_file_name)
print('Configuration : ', pkconfig.conf_column)
all_features = pd.read_excel("./config/" + pkconfig.configuration_file_name, index_col=0)

Configuration file:  CashIA_ConfFile.xlsx
Configuration :  NV_CC_CS

c:\Users\juan_\.conda\envs\cashia_env\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [4]:
features = all_features[all_features[pkconfig.conf_column] == 'Sí']
features

,NV_Agt,RNV_Agt,NV_CC,RNV_CC,NV_Agt_CS,RNV_Agt_CS,NV_CC_CS,RNV_CC_CS,Característica,Tipo de variable,Numérico,Min,Max,Tipo de dato,Sub tipo,Monetario,Sección,Observación,Unnamed: 19
ID,,,,,,,,,,,,,,,,,,,
9,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Monto,Predictor,1,900.0,17000.0,Cuantitativo,Entero,1,Crédito,NaN,x
11,Sí,Sí,Sí,No,Sí,Sí,Sí,Sí,Edad Solicitud,Predictor,1,18.0,100.0,Cuantitativo,Entero,0,Datos personales,Edad al hacer la solicitud,NaN
15,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Genero,Predictor,0,NaN,NaN,Categórico,Texto,0,Datos personales,NaN,NaN
18,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Dependientes,Predictor,1,0.0,10.0,Cuantitativo,Entero,0,Datos personales,NaN,x
34,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Ingresos,Predictor,1,0.0,50000.0,Cuantitativo,Entero,1,Estudio de ingresos,NaN,x
35,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Egresos,Predictor,1,0.0,50000.0,Cuantitativo,Entero,1,Estudio de egresos,NaN,x
51,Sí- Off,Sí- Off,Sí,Sí,Sí- Off,Sí- Off,Sí,Sí,Score CC,Predictor,1,0.0,820.0,Cuantitativo,Entero,0,Ciculo de Crédito,NaN,x
82,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Mes inicial,Predictor,1,1.0,12.0,Cuantitativo,Entero,0,Data Agregation,NaN,NaN
83,No,No,Sí,Sí,No,No,Sí,Sí,Odds,Predictor,1,0.0,9.0,Cuantitativo,Real,0,Data Agregation,NaN,x
84,Sí- Off,No,Sí,Sí,Sí- Off,No,Sí,Sí,Deficit,Predictor,1,-100000.0,100000.0,Cuantitativo,Entero,0,Data Agregation,NaN,x
85,Sí- Off,No,Sí,Sí,Sí- Off,No,Sí,Sí,IngresoPercapita,Predictor,1,0.0,40000.0,Cuantitativo,Real,1,Data Agregation,NaN,x
93,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Incobrable,Target,1,0.0,1.0,Categórico,Entero,0,NaN,NaN,NaN

In [5]:
features_to_use = set(features['Característica'].values)
features_to_use

{'Deficit',
 'Dependientes',
 'Edad Solicitud',
 'Egresos',
 'Genero',
 'Incobrable',
 'IngresoPercapita',
 'Ingresos',
 'Mes inicial',
 'Monto',
 'Odds',
 'Score CC'}

In [6]:
agregated_feautures = set(features[features['Sección'] == 'Data Agregation']['Característica'].values)
agregated_feautures

{'Deficit', 'IngresoPercapita', 'Mes inicial', 'Odds'}

### 1.1.2 Lectura de los datos de entrenamiento

In [7]:
print('Source file: ', pkconfig.source_file_name)
#data = pd.read_excel(pkconfig.source_file_name)
data = pd.read_csv("./data/" + pkconfig.source_file_name, index_col=0)

data_tracker = DataFrameEvolutionTracker(data)
data_tracker.to_dataframe()

if pkconfig.conf_column == "NV_Agt" or pkconfig.conf_column == "RNV_Agt":
    print("Agent score")
    data = data[data['Score Agt'] != 0]
else:
    print("Using CC score")

data_tracker.register_step(f"First filter for {pkconfig.conf_column}", data)
data_tracker.to_dataframe()

data.head()

Source file:  Data Set Cashia Entrenamiento.csv
Using CC score

C:\Users\juan_\AppData\Local\Temp\ipykernel_35872\725869802.py:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("./data/" + pkconfig.source_file_name, index_col=0)

,referencia,id_cliente,Fecha Inicial,fecha_finalizada,Monto,Edad Solicitud,Genero,Dependientes,CP,CP Aval,...,Frecuencia_Ant,vida_actual,Incobrable,score,Score_Ant,id_agente,score_agente,sem_inicio,semanas,Score Agt
id_solicitud,,,,,,,,,,,,,,,,,,,,,
71677,k7167799900407108,40710,08/02/2023,04/05/2023,8000,55,Femenino,0,94542,94542.0,...,0.000000,13,0,0.20455,0.0,123879,0.00000,576.0,7.0,0.00000
121744,k12174468622,68622,31/01/2024,09/07/2024,3000,18,Femenino,0,90800,90800.0,...,0.000000,23,1,0.63313,0.0,1309,0.57273,617.0,25.0,0.00000
66494,k66494000064945,6494,30/12/2022,05/05/2023,11000,24,Femenino,0,72014,72014.0,...,1.063799,18,0,0.20458,0.0,2005,0.05882,561.0,17.0,0.00000
66857,k66857000065890,6589,03/01/2023,04/05/2023,14000,45,Femenino,0,72014,72014.0,...,1.063799,18,0,0.20455,0.0,2005,0.05882,561.0,17.0,0.05882
72961,k7296110400351909,35190,21/02/2023,03/08/2023,5000,29,Femenino,0,90790,90790.0,...,1.198630,24,1,0.20455,0.0,2107,0.05882,568.0,17.0,0.00000

# Filtros especiales

## Borramos los datos de créditos no aprobados

In [8]:
# Quitamos esta línea en diciembre 2025 ya que en teoría sólo me pasan los créditos aprobados
# data = data[data['Aprobado'] == 1]
# data.shape

## De acuerdo a la columna de configuración selecionamos los datos

In [9]:
# Caso 1: Renovaciones
if pkconfig.conf_column == "NV_Agt":
    data = data[data['Categoria'] == "NV"]
    
elif pkconfig.conf_column == "RNV_Agt":
    data = data[(data['Categoria'] == "RNV")]
    
elif pkconfig.conf_column == "NV_CC":
    data = data[(data['Categoria'] == "NV")]
    
elif pkconfig.conf_column == "RNV_CC":
    data = data[(data['Categoria'] == "RNV")]

elif pkconfig.conf_column == "NV_Agt_CS":
    data = data[data['Categoria'] == "NV"]
    
elif pkconfig.conf_column == "RNV_Agt_CS":
    data = data[(data['Categoria'] == "RNV")]
    
elif pkconfig.conf_column == "NV_CC_CS":
    data = data[(data['Categoria'] == "NV")]
    
elif pkconfig.conf_column == "RNV_CC_CS":
    data = data[(data['Categoria'] == "RNV")]
    
else:
    print("Invalid option")
    exit()

data_tracker.register_step(f"Second filter for {pkconfig.conf_column}", data)
data_tracker.to_dataframe()

,Step,Rows,Columns,Column Names
0,Initialization,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
1,First filter for NV_CC_CS,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
2,Second filter for NV_CC_CS,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."

## 1.2 Explorar los datos

In [10]:
data_features = set(data.columns)
data_features

{'CP',
 'CP Aval',
 'Categoria',
 'Ciclo',
 'Dependientes',
 'Edad Solicitud',
 'Egresos',
 'Fecha Inicial',
 'Frecuencia_Ant',
 'Genero',
 'Incobrable',
 'Ingresos',
 'Monto',
 'Monto_Ant',
 'Plazo',
 'Score Agt',
 'Score CC',
 'Score_Ant',
 'Unidad',
 'fecha_finalizada',
 'id_agente',
 'id_cliente',
 'id_credito_ant',
 'id_fecha_finalizada_actual',
 'id_fecha_finalizada_ant',
 'id_fecha_impresion_actual',
 'id_fecha_impresion_ant',
 'pagado_cred_ant',
 'pagos_realizados_actual',
 'referencia',
 'score',
 'score_agente',
 'sem_inicio',
 'semanas',
 'tarifa_ant',
 'vida_actual',
 'vida_ant'}

In [11]:
features_to_drop = list(data_features - features_to_use)
# Removemos de la lista de elementos a borrar 'Fecha Inicial ya que la necesitaremos para los intervalos de aprendizaje'
features_to_drop.remove('Fecha Inicial')
features_to_drop

['Unidad',
 'fecha_finalizada',
 'semanas',
 'sem_inicio',
 'Score Agt',
 'Frecuencia_Ant',
 'id_fecha_finalizada_ant',
 'Monto_Ant',
 'vida_actual',
 'id_cliente',
 'referencia',
 'id_credito_ant',
 'score_agente',
 'Plazo',
 'Ciclo',
 'id_fecha_finalizada_actual',
 'CP Aval',
 'CP',
 'id_agente',
 'id_fecha_impresion_actual',
 'Score_Ant',
 'Categoria',
 'score',
 'tarifa_ant',
 'id_fecha_impresion_ant',
 'pagado_cred_ant',
 'vida_ant',
 'pagos_realizados_actual']

In [12]:
features

,NV_Agt,RNV_Agt,NV_CC,RNV_CC,NV_Agt_CS,RNV_Agt_CS,NV_CC_CS,RNV_CC_CS,Característica,Tipo de variable,Numérico,Min,Max,Tipo de dato,Sub tipo,Monetario,Sección,Observación,Unnamed: 19
ID,,,,,,,,,,,,,,,,,,,
9,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Monto,Predictor,1,900.0,17000.0,Cuantitativo,Entero,1,Crédito,NaN,x
11,Sí,Sí,Sí,No,Sí,Sí,Sí,Sí,Edad Solicitud,Predictor,1,18.0,100.0,Cuantitativo,Entero,0,Datos personales,Edad al hacer la solicitud,NaN
15,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Genero,Predictor,0,NaN,NaN,Categórico,Texto,0,Datos personales,NaN,NaN
18,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Dependientes,Predictor,1,0.0,10.0,Cuantitativo,Entero,0,Datos personales,NaN,x
34,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Ingresos,Predictor,1,0.0,50000.0,Cuantitativo,Entero,1,Estudio de ingresos,NaN,x
35,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Egresos,Predictor,1,0.0,50000.0,Cuantitativo,Entero,1,Estudio de egresos,NaN,x
51,Sí- Off,Sí- Off,Sí,Sí,Sí- Off,Sí- Off,Sí,Sí,Score CC,Predictor,1,0.0,820.0,Cuantitativo,Entero,0,Ciculo de Crédito,NaN,x
82,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Mes inicial,Predictor,1,1.0,12.0,Cuantitativo,Entero,0,Data Agregation,NaN,NaN
83,No,No,Sí,Sí,No,No,Sí,Sí,Odds,Predictor,1,0.0,9.0,Cuantitativo,Real,0,Data Agregation,NaN,x
84,Sí- Off,No,Sí,Sí,Sí- Off,No,Sí,Sí,Deficit,Predictor,1,-100000.0,100000.0,Cuantitativo,Entero,0,Data Agregation,NaN,x
85,Sí- Off,No,Sí,Sí,Sí- Off,No,Sí,Sí,IngresoPercapita,Predictor,1,0.0,40000.0,Cuantitativo,Real,1,Data Agregation,NaN,x
93,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Incobrable,Target,1,0.0,1.0,Categórico,Entero,0,NaN,NaN,NaN

In [13]:
int_features_list = features[(features['Sub tipo'] == "Entero") & (features['Sección'] != "Data Agregation")]
int_features_list = int_features_list['Característica'].unique()
int_features_list = list(int_features_list)

In [14]:
int_features_list

['Monto',
 'Edad Solicitud',
 'Dependientes',
 'Ingresos',
 'Egresos',
 'Score CC',
 'Incobrable']

In [15]:
all_features

,NV_Agt,RNV_Agt,NV_CC,RNV_CC,NV_Agt_CS,RNV_Agt_CS,NV_CC_CS,RNV_CC_CS,Característica,Tipo de variable,Numérico,Min,Max,Tipo de dato,Sub tipo,Monetario,Sección,Observación,Unnamed: 19
ID,,,,,,,,,,,,,,,,,,,
1,No,No,No,No,No,No,No,No,Id Solicitud,Predictor,1,0.0,999999.0,Cuantitativo entero,Entero,0,NaN,NaN,NaN
2,Sí- Off,No,Sí- Off,Sí- Off,Sí- Off,No,Sí- Off,Sí- Off,Plazo,Predictor,1,9.0,27.0,Categórico,Entero,0,Crédito,NaN,NaN
3,No,No,Sí- Off,Sí- Off,No,No,Sí- Off,Sí- Off,Categoria,Predictor,0,NaN,NaN,Categórico,Texto,0,Crédito,NaN,NaN
4,Sí,Sí,Sí,Sí,No,No,No,No,Unidad,Predictor,0,NaN,NaN,Categórico,Texto,0,Crédito,NaN,x
5,No,No,No,No,No,No,No,No,Zona,Predictor,0,NaN,NaN,Categórico,Texto,0,Crédito,"Mapearlo a ""unidad"" ya que son muchos valores",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,Sí,Sí,Sí,Sí,No,No,No,No,CP_Longitud,Predictor,1,-180.0,180.0,Cuantitativo,Real,0,Data Agregation,NaN,x
90,Sí- Off,No,Sí,Sí,Sí- Off,No,No,No,CP_Aval_Latitud,Predictor,1,-90.0,90.0,Cuantitativo,Real,0,Data Agregation,NaN,x
91,Sí- Off,No,Sí,Sí,Sí- Off,No,No,No,CP_Aval_Longitud,Predictor,1,-180.0,180.0,Cuantitativo,Real,0,Data Agregation,NaN,x
92,No,No,No,No,No,No,No,No,Score,Target,1,0.0,10.0,Cuantitativo real,Real,0,NaN,NaN,NaN
93,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Incobrable,Target,1,0.0,1.0,Categórico,Entero,0,NaN,NaN,NaN

In [16]:
if ('CP' not in features_to_use) and (('CP_Latitud' in features_to_use)| ('CP_Longitud' in features_to_use)):
    int_features_list.append('CP')
    
if ('CP Aval' not in features_to_use) and (('CP_Aval_Latitud' in features_to_use) | ('CP_Aval_Longitud' in features_to_use)):
    int_features_list.append('CP Aval')                                        

if ('Score CC' not in features_to_use) and 'Odds' in features_to_use:
    int_features_list.append('Score CC')

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48024 entries, 71677 to 124200
Data columns (total 37 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   referencia                  48024 non-null  object
 1   id_cliente                  48024 non-null  int64
 2   Fecha Inicial               48024 non-null  object
 3   fecha_finalizada            32759 non-null  object
 4   Monto                       48024 non-null  int64
 5   Edad Solicitud              48024 non-null  int64
 6   Genero                      48024 non-null  object
 7   Dependientes                48024 non-null  int64
 8   CP                          48024 non-null  int64
 9   CP Aval                     47435 non-null  object
 10  Ingresos                    48003 non-null  float64
 11  Egresos                     48024 non-null  float64
 12  Score CC                    48024 non-null  object
 13  Plazo                       48024 non-null  object
 14  Categoria                   48024 non-null  object
 15  Unidad                      48024 non-null  object
 16  Ciclo                       48024 non-null  int64
 17  id_credito_ant              13 non-null     float64
 18  Monto_Ant                   13 non-null     float64
 19  tarifa_ant                  13 non-null     float64
 20  pagado_cred_ant             13 non-null     float64
 21  id_fecha_impresion_ant      13 non-null     float64
 22  id_fecha_finalizada_ant     13 non-null     float64
 23  id_fecha_impresion_actual   48024 non-null  int64
 24  id_fecha_finalizada_actual  48024 non-null  int64
 25  pagos_realizados_actual     48024 non-null  int64
 26  vida_ant                    13 non-null     float64
 27  Frecuencia_Ant              48024 non-null  float64
 28  vida_actual                 48024 non-null  int64
 29  Incobrable                  48024 non-null  int64
 30  score                       48024 non-null  float64
 31  Score_Ant                   48024 non-null  float64
 32  id_agente                   48024 non-null  object
 33  score_agente                47554 non-null  float64
 34  sem_inicio                  47554 non-null  float64
 35  semanas                     47554 non-null  float64
 36  Score Agt                   47583 non-null  float64
dtypes: float64(16), int64(11), object(10)
memory usage: 13.9+ MB

In [18]:
data.isnull().sum()

referencia                        0
id_cliente                        0
Fecha Inicial                     0
fecha_finalizada              15265
Monto                             0
Edad Solicitud                    0
Genero                            0
Dependientes                      0
CP                                0
CP Aval                         589
Ingresos                         21
Egresos                           0
Score CC                          0
Plazo                             0
Categoria                         0
Unidad                            0
Ciclo                             0
id_credito_ant                48011
Monto_Ant                     48011
tarifa_ant                    48011
pagado_cred_ant               48011
id_fecha_impresion_ant        48011
id_fecha_finalizada_ant       48011
id_fecha_impresion_actual         0
id_fecha_finalizada_actual        0
pagos_realizados_actual           0
vida_ant                      48011
Frecuencia_Ant                    0
vida_actual                       0
Incobrable                        0
score                             0
Score_Ant                         0
id_agente                         0
score_agente                    470
sem_inicio                      470
semanas                         470
Score Agt                       441
dtype: int64

## 1.3 Limpiar los datos

In [19]:
quantitative_features = set(features[(features['Tipo de dato'] == 'Cuantitativo') & (features['Tipo de variable'] == 'Predictor')]['Característica'].values)
quantitative_features

{'Deficit',
 'Dependientes',
 'Edad Solicitud',
 'Egresos',
 'IngresoPercapita',
 'Ingresos',
 'Mes inicial',
 'Monto',
 'Odds',
 'Score CC'}

In [20]:
categorical_features = set(features[(features['Tipo de dato'] == 'Categórico') & (features['Tipo de variable'] == 'Predictor')]['Característica'].values)
categorical_features

{'Genero'}

### 1.3.1 Limpiar ingresos de conyuge para los que tienen NA poner "Desconocido"

In [21]:
if 'Ingreso Conyuge' in features_to_use: 
    pkdp.clean_ingreso_conyuge(data)
data_tracker.register_step(f"Cleaning datos conyuge", data)
data_tracker.to_dataframe()

,Step,Rows,Columns,Column Names
0,Initialization,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
1,First filter for NV_CC_CS,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
2,Second filter for NV_CC_CS,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
3,Cleaning datos conyuge,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."

### 1.3.1b

In [22]:
#pk.clean_incobrable(data)

### 1.3.2 Poner los egresos igual a sus ingresos a aquellos que tienen vacío en egresos

In [23]:
pkdp.clean_egresos(data)
data_tracker.register_step(f"Cleaning egresos", data)
data_tracker.to_dataframe()

,Step,Rows,Columns,Column Names
0,Initialization,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
1,First filter for NV_CC_CS,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
2,Second filter for NV_CC_CS,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
3,Cleaning datos conyuge,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
4,Cleaning egresos,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."

In [24]:
data.isnull().sum()

referencia                        0
id_cliente                        0
Fecha Inicial                     0
fecha_finalizada              15265
Monto                             0
Edad Solicitud                    0
Genero                            0
Dependientes                      0
CP                                0
CP Aval                         589
Ingresos                         21
Egresos                           0
Score CC                          0
Plazo                             0
Categoria                         0
Unidad                            0
Ciclo                             0
id_credito_ant                48011
Monto_Ant                     48011
tarifa_ant                    48011
pagado_cred_ant               48011
id_fecha_impresion_ant        48011
id_fecha_finalizada_ant       48011
id_fecha_impresion_actual         0
id_fecha_finalizada_actual        0
pagos_realizados_actual           0
vida_ant                      48011
Frecuencia_Ant                    0
vida_actual                       0
Incobrable                        0
score                             0
Score_Ant                         0
id_agente                         0
score_agente                    470
sem_inicio                      470
semanas                         470
Score Agt                       441
dtype: int64

In [25]:
raw_data = features_to_use-agregated_feautures
raw_data

{'Dependientes',
 'Edad Solicitud',
 'Egresos',
 'Genero',
 'Incobrable',
 'Ingresos',
 'Monto',
 'Score CC'}

In [26]:
data[list(raw_data)].isnull().sum()

Monto              0
Egresos            0
Ingresos          21
Genero             0
Edad Solicitud     0
Dependientes       0
Score CC           0
Incobrable         0
dtype: int64

### 1.3.3. Llenamos con "Unknown" los valores de columnas categóricas vacias

In [27]:
#data[list(categorical_features-agregated_feautures)] = data[list(categorical_features-agregated_feautures)].fillna('Unknown')

### 1.3.4 Borrar renglones con datos nulos en las columnas que se usarán en el modelo

In [28]:
data = data.dropna(subset=list(features_to_use-agregated_feautures))
data_tracker.register_step(f"Cleaning for columns with null", data)
data_tracker.to_dataframe()

,Step,Rows,Columns,Column Names
0,Initialization,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
1,First filter for NV_CC_CS,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
2,Second filter for NV_CC_CS,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
3,Cleaning datos conyuge,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
4,Cleaning egresos,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
5,Cleaning for columns with null,48003,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."

In [29]:
data.isnull().sum()

referencia                        0
id_cliente                        0
Fecha Inicial                     0
fecha_finalizada              15255
Monto                             0
Edad Solicitud                    0
Genero                            0
Dependientes                      0
CP                                0
CP Aval                         589
Ingresos                          0
Egresos                           0
Score CC                          0
Plazo                             0
Categoria                         0
Unidad                            0
Ciclo                             0
id_credito_ant                47990
Monto_Ant                     47990
tarifa_ant                    47990
pagado_cred_ant               47990
id_fecha_impresion_ant        47990
id_fecha_finalizada_ant       47990
id_fecha_impresion_actual         0
id_fecha_finalizada_actual        0
pagos_realizados_actual           0
vida_ant                      47990
Frecuencia_Ant                    0
vida_actual                       0
Incobrable                        0
score                             0
Score_Ant                         0
id_agente                         0
score_agente                    470
sem_inicio                      470
semanas                         470
Score Agt                       441
dtype: int64

### 1.3.5 Convertir a entero las columnas que deberían ser entero y no lo son

In [30]:
# 1) Convertir a numérico con NaN donde haya "NC" o vacío
data[int_features_list] = data[int_features_list].apply(
    pd.to_numeric, errors='coerce', downcast='integer'
)
data[int_features_list].isnull().sum()

Monto                 0
Edad Solicitud        0
Dependientes          0
Ingresos              0
Egresos               0
Score CC          21912
Incobrable            0
dtype: int64

In [31]:
# 2) Eliminar filas con NaN en esas columnas
data = data.dropna(subset=int_features_list)

# 3) Forzar a int (si quieres asegurarte que sean int "normales")
data[int_features_list] = data[int_features_list].astype(int)

In [32]:
data_tracker.register_step(f"Cleaning int features with dropna", data)
data_tracker.to_dataframe()

,Step,Rows,Columns,Column Names
0,Initialization,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
1,First filter for NV_CC_CS,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
2,Second filter for NV_CC_CS,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
3,Cleaning datos conyuge,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
4,Cleaning egresos,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
5,Cleaning for columns with null,48003,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
6,Cleaning int features with dropna,26091,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."

### 1.3.5 Convertir a float (Real) las columnas que deberían ser flot y no lo son

In [33]:
float_features_list = features[(features['Sub tipo'] == "Real") & (features['Sección'] != "Data Agregation")]['Característica'].unique()
float_features_list = list(float_features_list)

In [34]:
# if ('Score CC' not in features_to_use) and ('Odds' in features_to_use):
#     float_features_list.append('Score CC')    
# display(float_features_list)

In [35]:
# Convertir todo a floats (con NaN donde haya errores)
data[float_features_list] = data[float_features_list].apply(
    lambda col: pd.to_numeric(col, errors='coerce')
)

# Asegurar float64
data[float_features_list] = data[float_features_list].astype(float)

# Eliminar filas con problemas
data = data.dropna(subset=float_features_list)

print(data[float_features_list].info())
data_tracker.register_step(f"Cleaning na floats", data)
data_tracker.to_dataframe()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26091 entries, 71677 to 124200
Empty DataFrame
None

,Step,Rows,Columns,Column Names
0,Initialization,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
1,First filter for NV_CC_CS,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
2,Second filter for NV_CC_CS,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
3,Cleaning datos conyuge,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
4,Cleaning egresos,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
5,Cleaning for columns with null,48003,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
6,Cleaning int features with dropna,26091,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
7,Cleaning na floats,26091,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."

### 1.3.6 Identificar características cuantitativas y cualitativas

In [36]:
for feature in quantitative_features : 
    if feature not in agregated_feautures:
        pkdp.categorical_print_values(feature, data)
        print("-----------------------")

Monto
3000     13086
5000      6581
4000      1948
3500       675
10000      593
6000       505
7000       414
4500       386
8000       349
2000       303
15000      228
17000      147
12000      103
9000        91
5500        85
11000       67
2500        66
6500        54
7500        50
13000       29
8500        25
10500       20
9500        19
4800        18
3800        18
3900        18
3300        18
4900        15
3700        15
4600        14
3600        14
3400        14
3200        13
12500       12
3100        12
11500       11
4400        10
4100        10
14000        8
4300         8
13500        7
16000        6
4700         6
4200         5
2200         4
15500        3
2300         2
2700         1
12300        1
5100         1
14500        1
2100         1
2600         1
Name: Monto, dtype: int64
-----------------------
Egresos
5000     2673
0        2640
4000     2295
6000     1941
3000     1811
         ...
8750        1
2870        1
56000       1
2698        1
2380        1
Name: Egresos, Length: 479, dtype: int64
-----------------------
Ingresos
0         6401
8000      2502
10000     2345
12000     2055
6000      1151
          ...
1700         1
36500        1
185500       1
36000        1
1535         1
Name: Ingresos, Length: 340, dtype: int64
-----------------------
Edad Solicitud
19    825
18    807
32    750
33    744
34    700
29    697
28    696
22    691
36    684
31    680
30    677
26    674
27    662
20    658
23    657
21    653
24    652
37    645
25    635
35    631
39    626
38    615
43    613
40    607
41    595
42    594
44    566
46    561
45    557
47    516
50    516
48    512
49    477
51    456
53    448
52    446
54    399
55    359
56    354
57    310
58    303
59    258
61    252
60    245
62    202
63    187
65    163
64    155
66    114
68    104
67    101
69     60
70      2
Name: Edad Solicitud, dtype: int64
-----------------------
Dependientes
0     13301
1      7129
2      4161
3      1222
4       222
5        25
6        15
7         8
10        3
9         3
8         2
Name: Dependientes, dtype: int64
-----------------------
Score CC
0      2513
449     224
425     219
412     207
427     205
       ...
743       1
328       1
330       1
730       1
304       1
Name: Score CC, Length: 436, dtype: int64
-----------------------

In [37]:
data.head(5)

,referencia,id_cliente,Fecha Inicial,fecha_finalizada,Monto,Edad Solicitud,Genero,Dependientes,CP,CP Aval,...,Frecuencia_Ant,vida_actual,Incobrable,score,Score_Ant,id_agente,score_agente,sem_inicio,semanas,Score Agt
id_solicitud,,,,,,,,,,,,,,,,,,,,,
71677,k7167799900407108,40710,08/02/2023,04/05/2023,8000,55,Femenino,0,94542,94542.0,...,0.0,13,0,0.20455,0.0,123879,0.00000,576.0,7.0,0.00000
121744,k12174468622,68622,31/01/2024,09/07/2024,3000,18,Femenino,0,90800,90800.0,...,0.0,23,1,0.63313,0.0,1309,0.57273,617.0,25.0,0.00000
69758,k6975899900395917,39591,25/01/2023,12/05/2023,3000,18,Femenino,0,62748,62748.0,...,0.0,16,0,0.20456,0.0,2206,0.17940,564.0,17.0,0.00000
72809,k7280999900413583,41358,15/02/2023,05/05/2023,3000,62,Femenino,0,62748,62748.0,...,0.0,12,0,0.20456,0.0,2206,0.16130,567.0,17.0,0.17035
66301,k6630110001200377482,37748,02/01/2023,30/03/2023,3000,35,Femenino,0,94347,94347.0,...,0.0,13,0,0.20456,0.0,2207,0.17395,561.0,17.0,0.00000

In [38]:
for feature in categorical_features :
    if feature not in agregated_feautures:
        pkdp.categorical_print_values(feature, data)
        print("-----------------------")

Genero
Femenino     18753
Masculino     7338
Name: Genero, dtype: int64
-----------------------

### 1.3.7 Limpiar datos numéricos

In [39]:
numeric_features = features[(features['Numérico'] == 1) & (features['Sección'] != 'Data Agregation')]  
display(numeric_features)

,NV_Agt,RNV_Agt,NV_CC,RNV_CC,NV_Agt_CS,RNV_Agt_CS,NV_CC_CS,RNV_CC_CS,Característica,Tipo de variable,Numérico,Min,Max,Tipo de dato,Sub tipo,Monetario,Sección,Observación,Unnamed: 19
ID,,,,,,,,,,,,,,,,,,,
9,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Monto,Predictor,1,900.0,17000.0,Cuantitativo,Entero,1,Crédito,NaN,x
11,Sí,Sí,Sí,No,Sí,Sí,Sí,Sí,Edad Solicitud,Predictor,1,18.0,100.0,Cuantitativo,Entero,0,Datos personales,Edad al hacer la solicitud,NaN
18,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Dependientes,Predictor,1,0.0,10.0,Cuantitativo,Entero,0,Datos personales,NaN,x
34,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Ingresos,Predictor,1,0.0,50000.0,Cuantitativo,Entero,1,Estudio de ingresos,NaN,x
35,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Egresos,Predictor,1,0.0,50000.0,Cuantitativo,Entero,1,Estudio de egresos,NaN,x
51,Sí- Off,Sí- Off,Sí,Sí,Sí- Off,Sí- Off,Sí,Sí,Score CC,Predictor,1,0.0,820.0,Cuantitativo,Entero,0,Ciculo de Crédito,NaN,x
93,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Incobrable,Target,1,0.0,1.0,Categórico,Entero,0,NaN,NaN,NaN

In [40]:
pkdp.print_sizes(data)
for index, row in numeric_features.iterrows():
    print(f"Column {row['Característica']} max value found: {data[row['Característica']].max()}")
    pkdp.clean_numeric_data(data, row['Característica'], row['Min'], row['Max'])
    print("=================================================")
pkdp.print_sizes(data)

Rows: 26091
Columns: 37
Max index: 264422
Column Monto max value found: 17000
..=================================================
Column Edad Solicitud max value found: 70
..=================================================
Column Dependientes max value found: 10
..=================================================
Column Ingresos max value found: 185500
..Total of incorrect registers: 43
For example: minvalue:0.0 maxvalue:50000.0 found 68000
=================================================
Column Egresos max value found: 600000
..Total of incorrect registers: 28
For example: minvalue:0.0 maxvalue:50000.0 found 90000
=================================================
Column Score CC max value found: 769
..=================================================
Column Incobrable max value found: 1
..=================================================
Rows: 26020
Columns: 37
Max index: 264422

In [41]:
data_tracker.register_step(f"Cleaning numeric data min max", data)
data_tracker.to_dataframe()

,Step,Rows,Columns,Column Names
0,Initialization,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
1,First filter for NV_CC_CS,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
2,Second filter for NV_CC_CS,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
3,Cleaning datos conyuge,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
4,Cleaning egresos,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
5,Cleaning for columns with null,48003,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
6,Cleaning int features with dropna,26091,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
7,Cleaning na floats,26091,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
8,Cleaning numeric data min max,26020,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."

In [42]:
data.head()

,referencia,id_cliente,Fecha Inicial,fecha_finalizada,Monto,Edad Solicitud,Genero,Dependientes,CP,CP Aval,...,Frecuencia_Ant,vida_actual,Incobrable,score,Score_Ant,id_agente,score_agente,sem_inicio,semanas,Score Agt
id_solicitud,,,,,,,,,,,,,,,,,,,,,
71677,k7167799900407108,40710,08/02/2023,04/05/2023,8000,55,Femenino,0,94542,94542.0,...,0.0,13,0,0.20455,0.0,123879,0.00000,576.0,7.0,0.00000
121744,k12174468622,68622,31/01/2024,09/07/2024,3000,18,Femenino,0,90800,90800.0,...,0.0,23,1,0.63313,0.0,1309,0.57273,617.0,25.0,0.00000
69758,k6975899900395917,39591,25/01/2023,12/05/2023,3000,18,Femenino,0,62748,62748.0,...,0.0,16,0,0.20456,0.0,2206,0.17940,564.0,17.0,0.00000
72809,k7280999900413583,41358,15/02/2023,05/05/2023,3000,62,Femenino,0,62748,62748.0,...,0.0,12,0,0.20456,0.0,2206,0.16130,567.0,17.0,0.17035
66301,k6630110001200377482,37748,02/01/2023,30/03/2023,3000,35,Femenino,0,94347,94347.0,...,0.0,13,0,0.20456,0.0,2207,0.17395,561.0,17.0,0.00000

# 2 Data agregation

## 2.1 Agregar $Deficit = Ingresos - Egresos$

In [43]:
if 'Deficit' in quantitative_features:
    data['Deficit'] = data['Ingresos']-data['Egresos']
#quantitative_features.add('Deficit')

## 2.2 Agregar ingreso per capita

In [44]:
if 'IngresoPercapita' in  quantitative_features:
    data['IngresoPercapita'] = data['Ingresos']/(data['Dependientes']+1)
#quantitative_features.add('IngresoPercapita')

## 2.2 Agregar la zona a partir del Codigo Postal

In [45]:
#if 'TipoZona' in categorical_features:
#    CP_to_Zone = pd.read_excel("./CP_To_Zone.xlsx", index_col=0)
#    CP_Zone_set = set(CP_to_Zone.index)
#    data['TipoZona'] = data.apply(lambda x: CP_to_Zone.loc[x['CP']].Zona if x['CP'] in CP_Zone_set 
#                                  else "Unknown", axis=1)
#    data.head(5)

In [46]:
cp_manager = pm_mxgeo.MX_CP_manager('./mlp/inputs/MX_CP_CoordZone.csv')

In [47]:
data.columns

Index(['referencia', 'id_cliente', 'Fecha Inicial', 'fecha_finalizada',
       'Monto', 'Edad Solicitud', 'Genero', 'Dependientes', 'CP', 'CP Aval',
       'Ingresos', 'Egresos', 'Score CC', 'Plazo', 'Categoria', 'Unidad',
       'Ciclo', 'id_credito_ant', 'Monto_Ant', 'tarifa_ant', 'pagado_cred_ant',
       'id_fecha_impresion_ant', 'id_fecha_finalizada_ant',
       'id_fecha_impresion_actual', 'id_fecha_finalizada_actual',
       'pagos_realizados_actual', 'vida_ant', 'Frecuencia_Ant', 'vida_actual',
       'Incobrable', 'score', 'Score_Ant', 'id_agente', 'score_agente',
       'sem_inicio', 'semanas', 'Score Agt', 'Deficit', 'IngresoPercapita'],
      dtype='object')

In [48]:
data

,referencia,id_cliente,Fecha Inicial,fecha_finalizada,Monto,Edad Solicitud,Genero,Dependientes,CP,CP Aval,...,Incobrable,score,Score_Ant,id_agente,score_agente,sem_inicio,semanas,Score Agt,Deficit,IngresoPercapita
id_solicitud,,,,,,,,,,,,,,,,,,,,,
71677,k7167799900407108,40710,08/02/2023,04/05/2023,8000,55,Femenino,0,94542,94542.0,...,0,0.20455,0.0,123879,0.00000,576.0,7.0,0.000000,-4000,0.0
121744,k12174468622,68622,31/01/2024,09/07/2024,3000,18,Femenino,0,90800,90800.0,...,1,0.63313,0.0,1309,0.57273,617.0,25.0,0.000000,3000,6000.0
69758,k6975899900395917,39591,25/01/2023,12/05/2023,3000,18,Femenino,0,62748,62748.0,...,0,0.20456,0.0,2206,0.17940,564.0,17.0,0.000000,3200,7200.0
72809,k7280999900413583,41358,15/02/2023,05/05/2023,3000,62,Femenino,0,62748,62748.0,...,0,0.20456,0.0,2206,0.16130,567.0,17.0,0.170350,-3000,0.0
66301,k6630110001200377482,37748,02/01/2023,30/03/2023,3000,35,Femenino,0,94347,94347.0,...,0,0.20456,0.0,2207,0.17395,561.0,17.0,0.000000,11000,15600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86913,k8691300900493934,49393,31/05/2023,13/02/2025,5000,40,Femenino,0,72770,72770.0,...,1,0.05814,0.0,P1594A,0.04904,657.0,16.0,1.760470,4000,8000.0
94056,k9405653593,53593,19/07/2023,15/12/2024,5000,29,Femenino,0,72840,72803.0,...,1,0.10624,0.0,P1594A,1.40224,661.0,3.0,1.515980,6000,6000.0
101852,k10185257870,57870,09/09/2023,28/11/2024,3000,19,Femenino,0,72803,72803.0,...,1,0.19025,0.0,P1594A,0.27397,657.0,5.0,1.147565,6500,6500.0
105378,k10537860016,60016,03/10/2023,29/07/2025,5000,22,Femenino,0,74180,74180.0,...,1,0.22261,0.0,P1594A,0.04197,657.0,39.0,0.947756,10000,10000.0
124200,k12420069962,69962,19/02/2024,NaN,3000,42,Masculino,0,74180,74180.0,...,1,0.35203,0.0,P1594A,0.14566,657.0,36.0,0.704653,4000,9000.0

In [49]:
if 'TipoZona' in categorical_features:
    data['index'] = data.index
    print(data.head(5))
    data = data.merge(cp_manager.cp_base[['CP', 'TipoZona']], left_on='CP', right_on='CP', how='left').fillna("Fake")
    data = data.set_index(['index'])

In [50]:
data

,referencia,id_cliente,Fecha Inicial,fecha_finalizada,Monto,Edad Solicitud,Genero,Dependientes,CP,CP Aval,...,Incobrable,score,Score_Ant,id_agente,score_agente,sem_inicio,semanas,Score Agt,Deficit,IngresoPercapita
id_solicitud,,,,,,,,,,,,,,,,,,,,,
71677,k7167799900407108,40710,08/02/2023,04/05/2023,8000,55,Femenino,0,94542,94542.0,...,0,0.20455,0.0,123879,0.00000,576.0,7.0,0.000000,-4000,0.0
121744,k12174468622,68622,31/01/2024,09/07/2024,3000,18,Femenino,0,90800,90800.0,...,1,0.63313,0.0,1309,0.57273,617.0,25.0,0.000000,3000,6000.0
69758,k6975899900395917,39591,25/01/2023,12/05/2023,3000,18,Femenino,0,62748,62748.0,...,0,0.20456,0.0,2206,0.17940,564.0,17.0,0.000000,3200,7200.0
72809,k7280999900413583,41358,15/02/2023,05/05/2023,3000,62,Femenino,0,62748,62748.0,...,0,0.20456,0.0,2206,0.16130,567.0,17.0,0.170350,-3000,0.0
66301,k6630110001200377482,37748,02/01/2023,30/03/2023,3000,35,Femenino,0,94347,94347.0,...,0,0.20456,0.0,2207,0.17395,561.0,17.0,0.000000,11000,15600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86913,k8691300900493934,49393,31/05/2023,13/02/2025,5000,40,Femenino,0,72770,72770.0,...,1,0.05814,0.0,P1594A,0.04904,657.0,16.0,1.760470,4000,8000.0
94056,k9405653593,53593,19/07/2023,15/12/2024,5000,29,Femenino,0,72840,72803.0,...,1,0.10624,0.0,P1594A,1.40224,661.0,3.0,1.515980,6000,6000.0
101852,k10185257870,57870,09/09/2023,28/11/2024,3000,19,Femenino,0,72803,72803.0,...,1,0.19025,0.0,P1594A,0.27397,657.0,5.0,1.147565,6500,6500.0
105378,k10537860016,60016,03/10/2023,29/07/2025,5000,22,Femenino,0,74180,74180.0,...,1,0.22261,0.0,P1594A,0.04197,657.0,39.0,0.947756,10000,10000.0
124200,k12420069962,69962,19/02/2024,NaN,3000,42,Masculino,0,74180,74180.0,...,1,0.35203,0.0,P1594A,0.14566,657.0,36.0,0.704653,4000,9000.0

In [51]:
data.columns

Index(['referencia', 'id_cliente', 'Fecha Inicial', 'fecha_finalizada',
       'Monto', 'Edad Solicitud', 'Genero', 'Dependientes', 'CP', 'CP Aval',
       'Ingresos', 'Egresos', 'Score CC', 'Plazo', 'Categoria', 'Unidad',
       'Ciclo', 'id_credito_ant', 'Monto_Ant', 'tarifa_ant', 'pagado_cred_ant',
       'id_fecha_impresion_ant', 'id_fecha_finalizada_ant',
       'id_fecha_impresion_actual', 'id_fecha_finalizada_actual',
       'pagos_realizados_actual', 'vida_ant', 'Frecuencia_Ant', 'vida_actual',
       'Incobrable', 'score', 'Score_Ant', 'id_agente', 'score_agente',
       'sem_inicio', 'semanas', 'Score Agt', 'Deficit', 'IngresoPercapita'],
      dtype='object')

## 2.3 Agregar "Tiene aval" a partir de CP_Aval

In [52]:
if 'Tiene aval' in categorical_features:
    data['Tiene aval'] = data.apply(lambda x: 0 if pd.isnull(x['CP Aval']) else 1, axis=1)

## 2.3 Agregar Latitud y Longitud a partir del CP

In [53]:
data

,referencia,id_cliente,Fecha Inicial,fecha_finalizada,Monto,Edad Solicitud,Genero,Dependientes,CP,CP Aval,...,Incobrable,score,Score_Ant,id_agente,score_agente,sem_inicio,semanas,Score Agt,Deficit,IngresoPercapita
id_solicitud,,,,,,,,,,,,,,,,,,,,,
71677,k7167799900407108,40710,08/02/2023,04/05/2023,8000,55,Femenino,0,94542,94542.0,...,0,0.20455,0.0,123879,0.00000,576.0,7.0,0.000000,-4000,0.0
121744,k12174468622,68622,31/01/2024,09/07/2024,3000,18,Femenino,0,90800,90800.0,...,1,0.63313,0.0,1309,0.57273,617.0,25.0,0.000000,3000,6000.0
69758,k6975899900395917,39591,25/01/2023,12/05/2023,3000,18,Femenino,0,62748,62748.0,...,0,0.20456,0.0,2206,0.17940,564.0,17.0,0.000000,3200,7200.0
72809,k7280999900413583,41358,15/02/2023,05/05/2023,3000,62,Femenino,0,62748,62748.0,...,0,0.20456,0.0,2206,0.16130,567.0,17.0,0.170350,-3000,0.0
66301,k6630110001200377482,37748,02/01/2023,30/03/2023,3000,35,Femenino,0,94347,94347.0,...,0,0.20456,0.0,2207,0.17395,561.0,17.0,0.000000,11000,15600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86913,k8691300900493934,49393,31/05/2023,13/02/2025,5000,40,Femenino,0,72770,72770.0,...,1,0.05814,0.0,P1594A,0.04904,657.0,16.0,1.760470,4000,8000.0
94056,k9405653593,53593,19/07/2023,15/12/2024,5000,29,Femenino,0,72840,72803.0,...,1,0.10624,0.0,P1594A,1.40224,661.0,3.0,1.515980,6000,6000.0
101852,k10185257870,57870,09/09/2023,28/11/2024,3000,19,Femenino,0,72803,72803.0,...,1,0.19025,0.0,P1594A,0.27397,657.0,5.0,1.147565,6500,6500.0
105378,k10537860016,60016,03/10/2023,29/07/2025,5000,22,Femenino,0,74180,74180.0,...,1,0.22261,0.0,P1594A,0.04197,657.0,39.0,0.947756,10000,10000.0
124200,k12420069962,69962,19/02/2024,NaN,3000,42,Masculino,0,74180,74180.0,...,1,0.35203,0.0,P1594A,0.14566,657.0,36.0,0.704653,4000,9000.0

In [54]:
if features_to_use.intersection(pkdp.latitud_longitud_features_set):
    
    if 'CP_Latitud'in features_to_use: 
        print("Seting CP_Latitud")
        data = cp_manager.set_geographic_coordinate(data,'CP', 'CP_Latitud', 'Latitud')
        print(data.columns)
        print("-----------------------")
    
    if 'CP_Longitud' in features_to_use: 
        print("Seting CP_Longitud")
        data = cp_manager.set_geographic_coordinate(data,'CP', 'CP_Longitud', 'Longitud')
        print(data.columns)
        print("-----------------------")

    if 'CP_Aval_Latitud' in features_to_use: 
        data = cp_manager.set_geographic_coordinate(data,'CP Aval','CP_Aval_Latitud', 'Latitud')
        print(data.columns)
        print("-----------------------")

    if 'CP_Aval_Longitud' in features_to_use: 
        data = cp_manager.set_geographic_coordinate(data,'CP Aval','CP_Aval_Longitud', 'Longitud')
        print(data.columns)
        print("-----------------------")

In [55]:
data

,referencia,id_cliente,Fecha Inicial,fecha_finalizada,Monto,Edad Solicitud,Genero,Dependientes,CP,CP Aval,...,Incobrable,score,Score_Ant,id_agente,score_agente,sem_inicio,semanas,Score Agt,Deficit,IngresoPercapita
id_solicitud,,,,,,,,,,,,,,,,,,,,,
71677,k7167799900407108,40710,08/02/2023,04/05/2023,8000,55,Femenino,0,94542,94542.0,...,0,0.20455,0.0,123879,0.00000,576.0,7.0,0.000000,-4000,0.0
121744,k12174468622,68622,31/01/2024,09/07/2024,3000,18,Femenino,0,90800,90800.0,...,1,0.63313,0.0,1309,0.57273,617.0,25.0,0.000000,3000,6000.0
69758,k6975899900395917,39591,25/01/2023,12/05/2023,3000,18,Femenino,0,62748,62748.0,...,0,0.20456,0.0,2206,0.17940,564.0,17.0,0.000000,3200,7200.0
72809,k7280999900413583,41358,15/02/2023,05/05/2023,3000,62,Femenino,0,62748,62748.0,...,0,0.20456,0.0,2206,0.16130,567.0,17.0,0.170350,-3000,0.0
66301,k6630110001200377482,37748,02/01/2023,30/03/2023,3000,35,Femenino,0,94347,94347.0,...,0,0.20456,0.0,2207,0.17395,561.0,17.0,0.000000,11000,15600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86913,k8691300900493934,49393,31/05/2023,13/02/2025,5000,40,Femenino,0,72770,72770.0,...,1,0.05814,0.0,P1594A,0.04904,657.0,16.0,1.760470,4000,8000.0
94056,k9405653593,53593,19/07/2023,15/12/2024,5000,29,Femenino,0,72840,72803.0,...,1,0.10624,0.0,P1594A,1.40224,661.0,3.0,1.515980,6000,6000.0
101852,k10185257870,57870,09/09/2023,28/11/2024,3000,19,Femenino,0,72803,72803.0,...,1,0.19025,0.0,P1594A,0.27397,657.0,5.0,1.147565,6500,6500.0
105378,k10537860016,60016,03/10/2023,29/07/2025,5000,22,Femenino,0,74180,74180.0,...,1,0.22261,0.0,P1594A,0.04197,657.0,39.0,0.947756,10000,10000.0
124200,k12420069962,69962,19/02/2024,NaN,3000,42,Masculino,0,74180,74180.0,...,1,0.35203,0.0,P1594A,0.14566,657.0,36.0,0.704653,4000,9000.0

In [56]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26020 entries, 71677 to 124200
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   referencia                  26020 non-null  object
 1   id_cliente                  26020 non-null  int64
 2   Fecha Inicial               26020 non-null  object
 3   fecha_finalizada            18571 non-null  object
 4   Monto                       26020 non-null  int32
 5   Edad Solicitud              26020 non-null  int32
 6   Genero                      26020 non-null  object
 7   Dependientes                26020 non-null  int32
 8   CP                          26020 non-null  int64
 9   CP Aval                     25814 non-null  object
 10  Ingresos                    26020 non-null  int32
 11  Egresos                     26020 non-null  int32
 12  Score CC                    26020 non-null  int32
 13  Plazo                       26020 non-null  object
 14  Categoria                   26020 non-null  object
 15  Unidad                      26020 non-null  object
 16  Ciclo                       26020 non-null  int64
 17  id_credito_ant              1 non-null      float64
 18  Monto_Ant                   1 non-null      float64
 19  tarifa_ant                  1 non-null      float64
 20  pagado_cred_ant             1 non-null      float64
 21  id_fecha_impresion_ant      1 non-null      float64
 22  id_fecha_finalizada_ant     1 non-null      float64
 23  id_fecha_impresion_actual   26020 non-null  int64
 24  id_fecha_finalizada_actual  26020 non-null  int64
 25  pagos_realizados_actual     26020 non-null  int64
 26  vida_ant                    1 non-null      float64
 27  Frecuencia_Ant              26020 non-null  float64
 28  vida_actual                 26020 non-null  int64
 29  Incobrable                  26020 non-null  int32
 30  score                       26020 non-null  float64
 31  Score_Ant                   26020 non-null  float64
 32  id_agente                   26020 non-null  object
 33  score_agente                25863 non-null  float64
 34  sem_inicio                  25863 non-null  float64
 35  semanas                     25863 non-null  float64
 36  Score Agt                   25871 non-null  float64
 37  Deficit                     26020 non-null  int32
 38  IngresoPercapita            26020 non-null  float64
dtypes: float64(15), int32(8), int64(7), object(9)
memory usage: 7.1+ MB

## 2.4 Agregar los odds de circulo de crédito

In [57]:
if ('Odds' in quantitative_features):
    score_bins = [-1, 235, 406, 433, 451, 465, 477, 489, 499, 509, 518, 528, 538, 548, 559, 571, 584, 598, 614, 634, 664, 861]
    odds = [0, 0.90, 1.20, 1.30, 1.50, 1.60, 1.80, 1.90, 2.00, 2.10, 2.20, 2.60, 2.75, 2.90, 3.20, 3.50, 4.00, 4.60, 5.30, 6.10, 8.30]

    data['Odds'] = pd.cut(data['Score CC'], score_bins, labels=odds)
    data['Odds'] = data['Odds'].astype(float)
    print(data[['Score CC', 'Odds']])

              Score CC  Odds
id_solicitud
71677              438  1.30
121744               0  0.00
69758                0  0.00
72809              430  1.20
66301              412  1.20
...                ...   ...
86913              486  1.80
94056              603  4.60
101852             546  2.75
105378             490  1.90
124200             505  2.00

[26020 rows x 2 columns]

In [58]:
quantitative_features

{'Deficit',
 'Dependientes',
 'Edad Solicitud',
 'Egresos',
 'IngresoPercapita',
 'Ingresos',
 'Mes inicial',
 'Monto',
 'Odds',
 'Score CC'}

In [59]:
data.columns

Index(['referencia', 'id_cliente', 'Fecha Inicial', 'fecha_finalizada',
       'Monto', 'Edad Solicitud', 'Genero', 'Dependientes', 'CP', 'CP Aval',
       'Ingresos', 'Egresos', 'Score CC', 'Plazo', 'Categoria', 'Unidad',
       'Ciclo', 'id_credito_ant', 'Monto_Ant', 'tarifa_ant', 'pagado_cred_ant',
       'id_fecha_impresion_ant', 'id_fecha_finalizada_ant',
       'id_fecha_impresion_actual', 'id_fecha_finalizada_actual',
       'pagos_realizados_actual', 'vida_ant', 'Frecuencia_Ant', 'vida_actual',
       'Incobrable', 'score', 'Score_Ant', 'id_agente', 'score_agente',
       'sem_inicio', 'semanas', 'Score Agt', 'Deficit', 'IngresoPercapita',
       'Odds'],
      dtype='object')

## 2.5 Agregar el número de mes en que se solicita el crédito

In [60]:
if ('Mes inicial' in quantitative_features):
    data['Fecha Inicial'] = pd.to_datetime(data['Fecha Inicial'], format='%d/%m/%Y')
    data['Mes inicial'] = data['Fecha Inicial'].dt.month

## 2.6 Transformación de columnas categóricas representadas como números

### 2.4.1 Mapear los estudios del cliente de un id entero a su significado

In [61]:
if 'Estudios' in features_to_use:
    nivel_educativo = {
        0: 'Sin Estudios',
        1: 'Primaria',
        2: 'Secundaria',
        3: 'Preparatoria',
        4: 'Técnica',
        5: 'Licenciatura',
        6: 'Maestría',
        7: 'Carrera Trunca'
    }
    data['Estudios'] = data['Estudios'].map(nivel_educativo)

In [62]:
data['Plazo'].head(5)

id_solicitud
71677     17 Sem
121744    17 Sem
69758     17 Sem
72809     17 Sem
66301     17 Sem
Name: Plazo, dtype: object

In [63]:
if 'Plazo' in features_to_use:
    plazo_pago = {
        9: '9 Sem', 
        13: '13 Sem',
        16: '16 Sem',  
        17: '17 Sem',
        26: '26 Sem', 
        27: '27 Sem', 
    }
    data['Plazo'] = data['Plazo'].map(plazo_pago)

In [64]:
data['Plazo'].head(5)

id_solicitud
71677     17 Sem
121744    17 Sem
69758     17 Sem
72809     17 Sem
66301     17 Sem
Name: Plazo, dtype: object

## 2.7 Usar solamente un numero N de dígitos en el código postal

In [65]:
#if pkconfig.zip_digits <= 4:
#    if 'CP' in features_to_use: pk.transform_CP(data,'CP', pkconfig.zip_digits)
#    if 'CP Aval' in features_to_use: pk.transform_CP(data,'CP Aval', pkconfig.zip_digits)

## Borrar las columnas que no serán usados

In [66]:
data = data.drop(labels=features_to_drop, axis=1)
data.head()

,Fecha Inicial,Monto,Edad Solicitud,Genero,Dependientes,Ingresos,Egresos,Score CC,Incobrable,Deficit,IngresoPercapita,Odds,Mes inicial
id_solicitud,,,,,,,,,,,,,
71677,2023-02-08,8000,55,Femenino,0,0,4000,438,0,-4000,0.0,1.3,2
121744,2024-01-31,3000,18,Femenino,0,6000,3000,0,1,3000,6000.0,0.0,1
69758,2023-01-25,3000,18,Femenino,0,7200,4000,0,0,3200,7200.0,0.0,1
72809,2023-02-15,3000,62,Femenino,0,0,3000,430,0,-3000,0.0,1.2,2
66301,2023-01-02,3000,35,Femenino,0,15600,4600,412,0,11000,15600.0,1.2,1

In [67]:
pkdp.print_sizes(data)

Rows: 26020
Columns: 13
Max index: 264422

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26020 entries, 71677 to 124200
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Fecha Inicial     26020 non-null  datetime64[ns]
 1   Monto             26020 non-null  int32
 2   Edad Solicitud    26020 non-null  int32
 3   Genero            26020 non-null  object
 4   Dependientes      26020 non-null  int32
 5   Ingresos          26020 non-null  int32
 6   Egresos           26020 non-null  int32
 7   Score CC          26020 non-null  int32
 8   Incobrable        26020 non-null  int32
 9   Deficit           26020 non-null  int32
 10  IngresoPercapita  26020 non-null  float64
 11  Odds              26020 non-null  float64
 12  Mes inicial       26020 non-null  int64
dtypes: datetime64[ns](1), float64(2), int32(8), int64(1), object(1)
memory usage: 2.0+ MB

In [69]:
data.dtypes

Fecha Inicial       datetime64[ns]
Monto                        int32
Edad Solicitud               int32
Genero                      object
Dependientes                 int32
Ingresos                     int32
Egresos                      int32
Score CC                     int32
Incobrable                   int32
Deficit                      int32
IngresoPercapita           float64
Odds                       float64
Mes inicial                  int64
dtype: object

In [70]:
data.head()
#data.to_excel(pkconfig.data_file_name)
data.to_csv("./data/" + pkconfig.data_file_name)

In [71]:
data_tracker.to_dataframe().to_csv("./data/" + pkconfig.conf_column + "_data_tracking.csv")

In [72]:
features_to_drop

['Unidad',
 'fecha_finalizada',
 'semanas',
 'sem_inicio',
 'Score Agt',
 'Frecuencia_Ant',
 'id_fecha_finalizada_ant',
 'Monto_Ant',
 'vida_actual',
 'id_cliente',
 'referencia',
 'id_credito_ant',
 'score_agente',
 'Plazo',
 'Ciclo',
 'id_fecha_finalizada_actual',
 'CP Aval',
 'CP',
 'id_agente',
 'id_fecha_impresion_actual',
 'Score_Ant',
 'Categoria',
 'score',
 'tarifa_ant',
 'id_fecha_impresion_ant',
 'pagado_cred_ant',
 'vida_ant',
 'pagos_realizados_actual']

In [73]:
time_now = datetime.now()

format_date_hour = "%Y-%m-%d %H:%M:%S"
date_and_hour = time_now.strftime(format_date_hour)

# Imprimir la fecha y hora
print("Ended at:", date_and_hour)

Ended at: 2026-06-11 21:10:20

In [74]:
data_tracker.to_dataframe()

,Step,Rows,Columns,Column Names
0,Initialization,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
1,First filter for NV_CC_CS,113630,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
2,Second filter for NV_CC_CS,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
3,Cleaning datos conyuge,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
4,Cleaning egresos,48024,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
5,Cleaning for columns with null,48003,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
6,Cleaning int features with dropna,26091,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
7,Cleaning na floats,26091,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."
8,Cleaning numeric data min max,26020,37,"[referencia, id_cliente, Fecha Inicial, fecha_..."

In [75]:
data.head(60)

,Fecha Inicial,Monto,Edad Solicitud,Genero,Dependientes,Ingresos,Egresos,Score CC,Incobrable,Deficit,IngresoPercapita,Odds,Mes inicial
id_solicitud,,,,,,,,,,,,,
71677,2023-02-08,8000,55,Femenino,0,0,4000,438,0,-4000,0.000000,1.30,2
121744,2024-01-31,3000,18,Femenino,0,6000,3000,0,1,3000,6000.000000,0.00,1
69758,2023-01-25,3000,18,Femenino,0,7200,4000,0,0,3200,7200.000000,0.00,1
72809,2023-02-15,3000,62,Femenino,0,0,3000,430,0,-3000,0.000000,1.20,2
66301,2023-01-02,3000,35,Femenino,0,15600,4600,412,0,11000,15600.000000,1.20,1
67288,2023-01-09,3000,22,Femenino,1,18000,6500,482,0,11500,9000.000000,1.80,1
67327,2023-01-06,3000,22,Femenino,2,15500,6900,502,0,8600,5166.666667,2.00,1
67340,2023-01-06,5000,39,Masculino,2,25000,7500,389,0,17500,8333.333333,0.90,1
67355,2023-01-06,3000,30,Femenino,2,9500,5500,449,0,4000,3166.666667,1.30,1
67519,2023-01-09,3000,50,Femenino,3,18000,5000,629,0,13000,4500.000000,5.30,1
69600,2023-01-24,3000,50,Masculino,0,22000,5200,435,0,16800,22000.000000,1.30,1
70423,2023-01-30,4000,32,Masculino,0,18000,6000,478,0,12000,18000.000000,1.80,1
71433,2023-02-07,3000,24,Femenino,3,10000,5000,449,0,5000,2500.000000,1.30,2
71915,2023-02-08,3000,55,Femenino,1,23000,6900,554,0,16100,11500.000000,2.90,2
72253,2023-02-11,3000,50,Femenino,0,19500,5800,518,0,13700,19500.000000,2.10,2
72560,2023-02-15,3000,33,Masculino,2,0,7000,0,0,-7000,0.000000,0.00,2
72648,2023-02-15,3000,56,Femenino,0,20000,6500,520,0,13500,20000.000000,2.20,2
67152,2023-01-04,3000,25,Femenino,0,11000,7000,485,0,4000,11000.000000,1.80,1
67589,2023-01-09,5000,43,Femenino,1,8200,5800,484,0,2400,4100.000000,1.80,1
67962,2023-01-11,5000,25,Femenino,0,18000,4000,451,0,14000,18000.000000,1.30,1
70527,2023-02-01,3000,51,Femenino,0,7000,0,0,0,7000,7000.000000,0.00,2
72307,2023-02-14,5000,40,Femenino,0,13000,1500,435,0,11500,13000.000000,1.30,2
72310,2023-02-14,5000,25,Femenino,0,14000,1000,652,0,13000,14000.000000,6.10,2
68151,2023-01-11,3000,69,Masculino,0,9900,0,439,0,9900,9900.000000,1.30,1
67402,2023-01-06,5000,46,Femenino,0,11000,0,469,0,11000,11000.000000,1.60,1
67835,2023-01-11,4700,34,Femenino,0,12000,0,542,0,12000,12000.000000,2.75,1
70452,2023-01-30,4000,32,Femenino,1,9000,2500,487,0,6500,4500.000000,1.80,1
70455,2023-01-30,4500,39,Femenino,2,8000,4500,652,0,3500,2666.666667,6.10,1
70919,2023-02-03,4500,64,Femenino,0,9000,4500,538,0,4500,9000.000000,2.60,2
76385,2023-03-13,4000,31,Femenino,1,8500,2500,460,0,6000,4250.000000,1.50,3
73144,2023-02-18,3000,42,Femenino,0,10000,2000,641,0,8000,10000.000000,6.10,2
73679,2023-02-22,3000,48,Femenino,1,6500,3500,607,0,3000,3250.000000,4.60,2
66962,2023-01-04,2000,23,Femenino,0,6300,0,623,0,6300,6300.000000,5.30,1
68122,2023-01-11,3500,43,Femenino,0,20000,0,661,0,20000,20000.000000,6.10,1
69853,2023-01-25,5000,37,Femenino,0,6000,0,460,0,6000,6000.000000,1.50,1
66303,2022-12-30,5000,34,Femenino,1,4500,2500,593,1,2000,2250.000000,4.00,12
66360,2022-12-30,7000,32,Femenino,0,6000,0,660,0,6000,6000.000000,6.10,12
67949,2023-01-11,5000,34,Femenino,0,9000,0,542,0,9000,9000.000000,2.75,1
68152,2023-01-13,6000,31,Femenino,2,9000,16000,447,0,-7000,3000.000000,1.30,1
68449,2023-01-14,6000,36,Femenino,0,15000,3000,433,0,12000,15000.000000,1.20,1
67871,2023-01-10,2000,36,Femenino,2,12000,6000,543,0,6000,4000.000000,2.75,1
79214,2023-04-05,3000,39,Masculino,2,6000,7000,685,0,-1000,2000.000000,8.30,4
67995,2023-01-11,3000,56,Femenino,0,10000,9000,449,0,1000,10000.000000,1.30,1
66678,2023-01-02,5000,42,Femenino,0,15000,0,615,0,15000,15000.000000,5.30,1
66683,2023-01-04,5000,31,Femenino,0,15000,0,433,0,15000,15000.000000,1.20,1
67542,2023-01-11,5000,46,Femenino,0,15000,0,424,0,15000,15000.000000,1.20,1
66411,2023-01-04,3000,27,Femenino,1,6000,4000,420,0,2000,3000.000000,1.20,1
67217,2023-01-04,5000,61,Femenino,2,1000,1000,494,0,0,333.333333,1.90,1
80315,2023-04-12,3000,53,Femenino,1,7000,4500,621,0,2500,3500.000000,5.30,4
70013,2023-01-25,5000,31,Femenino,1,8000,4000,649,0,4000,4000.000000,6.10,1
70015,2023-01-27,3000,24,Femenino,0,8000,0,539,1,8000,8000.000000,2.75,1
72076,2023-02-10,3000,49,Masculino,0,12000,4000,492,0,8000,12000.000000,1.90,2
72085,2023-02-10,3000,43,Femenino,1,7800,4000,661,0,3800,3900.000000,6.10,2
75849,2023-03-13,3000,27,Masculino,0,8000,4500,684,0,3500,8000.000000,8.30,3
101509,2023-09-06,3000,47,Femenino,1,9000,3600,0,1,5400,4500.000000,0.00,9
111406,2023-11-15,4000,44,Femenino,0,7200,4635,493,1,2565,7200.000000,1.90,11
96125,2023-08-02,3000,29,Femenino,0,8000,0,500,1,8000,8000.000000,2.00,8
86116,2023-05-24,3000,19,Femenino,0,12000,6000,0,1,6000,12000.000000,0.00,5
87033,2023-05-31,3000,26,Masculino,1,15000,4500,532,1,10500,7500.000000,2.60,5
113758,2023-12-08,3000,56,Femenino,1,32000,12000,438,1,20000,16000.000000,1.30,12

In [76]:
data = data.reset_index(drop=True)

In [77]:
data.tail(60)

,Fecha Inicial,Monto,Edad Solicitud,Genero,Dependientes,Ingresos,Egresos,Score CC,Incobrable,Deficit,IngresoPercapita,Odds,Mes inicial
25960,2023-11-13,3000,33,Femenino,0,12000,0,684,1,12000,12000.0,8.30,11
25961,2023-12-22,3000,49,Femenino,0,10000,3500,447,1,6500,10000.0,1.30,12
25962,2024-01-03,3000,60,Femenino,0,10000,7000,561,1,3000,10000.0,3.20,1
25963,2024-01-08,5000,58,Femenino,0,10000,4000,518,1,6000,10000.0,2.10,1
25964,2024-01-22,3000,22,Femenino,0,10000,5000,352,1,5000,10000.0,0.90,1
25965,2024-01-30,5000,45,Femenino,0,13000,7000,436,1,6000,13000.0,1.30,1
25966,2024-01-30,3000,54,Femenino,0,12000,4500,523,1,7500,12000.0,2.20,1
25967,2024-02-05,3000,22,Femenino,0,6000,4000,413,1,2000,6000.0,1.20,2
25968,2024-02-02,3000,33,Femenino,0,12000,4000,427,1,8000,12000.0,1.20,2
25969,2024-02-14,3000,30,Femenino,0,8000,5000,631,1,3000,8000.0,5.30,2
25970,2024-02-19,5000,46,Femenino,0,10000,7600,437,1,2400,10000.0,1.30,2
25971,2024-03-04,3000,26,Femenino,0,10000,6200,537,1,3800,10000.0,2.60,3
25972,2024-03-04,4000,20,Masculino,0,10000,6800,429,1,3200,10000.0,1.20,3
25973,2024-08-07,4500,43,Femenino,1,0,5000,400,1,-5000,0.0,0.90,8
25974,2024-08-12,3000,51,Masculino,3,0,5000,549,1,-5000,0.0,2.90,8
25975,2024-09-30,3000,37,Masculino,4,0,3600,481,1,-3600,0.0,1.80,9
25976,2024-10-09,5000,37,Femenino,0,0,4500,433,1,-4500,0.0,1.20,10
25977,2024-11-11,3000,31,Femenino,1,0,5000,487,1,-5000,0.0,1.80,11
25978,2024-11-27,3000,34,Masculino,3,10000,5000,412,1,5000,2500.0,1.20,11
25979,2024-11-22,5000,28,Femenino,1,10000,5000,413,1,5000,5000.0,1.20,11
25980,2024-11-27,3000,47,Femenino,0,0,6500,401,1,-6500,0.0,0.90,11
25981,2025-03-14,5000,49,Femenino,1,0,5000,477,1,-5000,0.0,1.60,3
25982,2025-05-26,17000,25,Femenino,1,0,7200,427,1,-7200,0.0,1.20,5
25983,2023-01-16,5000,39,Femenino,0,12000,0,457,1,12000,12000.0,1.50,1
25984,2023-02-25,4900,27,Femenino,0,12400,3700,471,1,8700,12400.0,1.60,2
25985,2023-04-26,3000,22,Masculino,0,8600,4000,427,1,4600,8600.0,1.20,4
25986,2023-06-07,5000,33,Masculino,0,12000,5000,447,1,7000,12000.0,1.30,6
25987,2023-06-17,5000,25,Femenino,0,10000,5000,497,1,5000,10000.0,1.90,6
25988,2023-06-28,3000,24,Femenino,0,2000,1200,453,1,800,2000.0,1.50,6
25989,2023-07-10,3000,24,Femenino,0,2000,1000,566,1,1000,2000.0,3.20,7
25990,2023-07-15,3000,28,Femenino,0,7000,4500,573,1,2500,7000.0,3.50,7
25991,2023-08-14,3000,24,Femenino,0,6000,0,603,1,6000,6000.0,4.60,8
25992,2023-09-12,3000,22,Femenino,0,10400,0,528,1,10400,10400.0,2.20,9
25993,2023-09-18,3000,29,Femenino,0,12600,0,631,1,12600,12600.0,5.30,9
25994,2023-09-20,3000,33,Femenino,0,13900,0,456,1,13900,13900.0,1.50,9
25995,2023-09-27,3000,19,Femenino,0,21000,0,0,1,21000,21000.0,0.00,9
25996,2023-12-27,3000,19,Femenino,0,6000,0,0,1,6000,6000.0,0.00,12
25997,2024-01-10,5000,18,Femenino,0,8000,4000,536,1,4000,8000.0,2.60,1
25998,2024-01-22,3000,38,Femenino,0,15000,7500,412,1,7500,15000.0,1.20,1
25999,2024-02-06,3000,21,Femenino,0,12000,6000,607,1,6000,12000.0,4.60,2
26000,2024-02-14,5000,59,Femenino,0,12000,0,477,1,12000,12000.0,1.60,2
26001,2024-02-26,5000,26,Femenino,0,13800,0,430,1,13800,13800.0,1.20,2
26002,2024-03-18,5000,38,Masculino,0,8000,4500,397,1,3500,8000.0,0.90,3
26003,2024-11-15,5000,25,Femenino,1,0,3000,566,1,-3000,0.0,3.20,11
26004,2024-11-19,3000,31,Femenino,1,8000,2500,427,1,5500,4000.0,1.20,11
26005,2024-11-19,3000,37,Femenino,4,0,7500,412,1,-7500,0.0,1.20,11
26006,2024-11-25,3000,41,Masculino,1,0,2500,433,1,-2500,0.0,1.20,11
26007,2024-11-27,3000,26,Masculino,1,0,2500,481,1,-2500,0.0,1.80,11
26008,2024-11-27,3000,21,Masculino,0,0,4000,426,1,-4000,0.0,1.20,11
26009,2025-01-15,12500,62,Femenino,0,0,3000,428,1,-3000,0.0,1.20,1
26010,2025-04-15,13500,41,Masculino,1,0,6000,0,1,-6000,0.0,0.00,4
26011,2025-04-16,10500,24,Femenino,1,0,7000,458,1,-7000,0.0,1.50,4
26012,2025-05-14,5000,25,Masculino,1,0,7000,482,1,-7000,0.0,1.80,5
26013,2023-12-08,4000,41,Femenino,0,8000,5000,663,1,3000,8000.0,6.10,12
26014,2024-02-05,5000,36,Femenino,0,6900,0,619,1,6900,6900.0,5.30,2
26015,2023-05-31,5000,40,Femenino,0,8000,4000,486,1,4000,8000.0,1.80,5
26016,2023-07-19,5000,29,Femenino,0,6000,0,603,1,6000,6000.0,4.60,7
26017,2023-09-09,3000,19,Femenino,0,6500,0,546,1,6500,6500.0,2.75,9
26018,2023-10-03,5000,22,Femenino,0,10000,0,490,1,10000,10000.0,1.90,10
26019,2024-02-19,3000,42,Masculino,0,9000,5000,505,1,4000,9000.0,2.00,2

In [78]:
# Imprimir la hora actual
print("Finalizado a las:", datetime.now().strftime("%H:%M:%S"))

# Hacer un sonido
if sys.platform.startswith("win"):
    import winsound
    winsound.Beep(1000, 500)  # Frecuencia de 1000 Hz, duración de 500 ms
    winsound.Beep(500, 500) 
    winsound.Beep(1000, 500) 
else:
    print('\a')  # Hace un beep en algunos sistemas UNIX
    
print('Configuration : ', pkconfig.conf_column)
pkdp.print_sizes(data)

Finalizado a las: 21:10:20
Configuration :  NV_CC_CS
Rows: 26020
Columns: 13
Max index: 26019